### ISSUE TITLE
Not able to import into a project

### ISSUE THREAD

**Issue by ChrisMBarr** [SongProOrg/songpro-javascript#34]
I believe this package might be built in an odd way that does not allow for a standard way of importing it into a project.  

I have tried a lot of different things, but in the end nothing works.  See my efforts here on the StackOverflow question which I won't repeat in this issue: https://stackoverflow.com/questions/76285992/including-js-package-import-in-a-typescript-project

To summarize though, I have a TypeScript project and none of the following imports do anything
```
import * as songpro from 'songpro'
const songpro = require('songpro');
const songpro = require('SongPro');
```

For all of them the `songpro` object is totally empty when I log it to the console, it has no methods or properties on it.

I'd love to get any advice from you if I am doing something wrong, but if not it would be fantastic if this project used a standard module system to allow for easy importing.

**Comment by spilth** [comment]
I just published your 0.1.2 version to NPM, so I think you should be set now?

At some point I'd love to sync up about a few things around the library but for now I'm happy to have including your updates and keep your project moving forward. Thanks for taking that on!

**Comment by ChrisMBarr** [comment]
Works like a charm!  thanks so much!  

FYI I am using this on my LyricConverter project: https://github.com/FiniteLooper/LyricConverter/tree/angular-rewrite
Still working on a few things as I have recently rewritten this years old project in TypeScript and Angular now.  But I hope to have it up and running soon. The link in that readme is not showing the latest changes yet

**Comment by spilth** [comment]
If you're looking for a bunch of SongPro files to test out, I've got a bunch here: https://github.com/spilth/mss.band/tree/main/source/songs

I also noticed your site expects a `.txt` extension for SongPro files instead of `.sng`

**Comment by ChrisMBarr** [comment]
the current version expects .sng, that one just isn't published in a live/interactive way anywhere yet.  Yes thanks I'll for sure add some of those for testing!

Here is the current SongPro input converter
https://github.com/FiniteLooper/LyricConverter/blob/angular-rewrite/src/app/convert/inputs/input-type-songpro.ts

and output converter
https://github.com/FiniteLooper/LyricConverter/blob/angular-rewrite/src/app/convert/outputs/output-type-songpro.ts

**Comment by ChrisMBarr** [comment]
@spilth FYI - just got the angular branch merged in & deployed here - please try it out and let me know if you have any issues!
http://finitelooper.github.io/LyricConverter/

**Comment by spilth** [comment]
@FiniteLooper I add a bunch of a songs from the mss project and it seemed to handle them all fine. Nice work!

**Comment by ChrisMBarr** [comment]
cool thanks!  I tried those song out too.  I mean reading those files it 100% dependent on your songpro library... so you actually did the hard work for that part!  I guess I'm curious about how it creates songpro files from other types.  Obviously it only deals with lyrics, so it won't have any chords or other fancy stuff
